services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: dbuser
      DATABASE_PORT: 5432
      DATABASE_USER: nestuser
      DATABASE_PASSWORD: dbpassword
      DATABASE_NAME: mydb
    depends_on:
      - postgres
    volumes:
      - docker build -f Dockerfile ./api/api:/usr/src/app
    command: yarn start:debug

volumes:
  postgres_data: